title: Guia do Usuário - Presence
description: Este é um guia para ajudar o usuário do aplicativo presence de presenças online a executrar as tearefas mais comuns no site.
theme: just-the-docs

url: https://presence-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  alunos:
    permalink: "/:collection/:path/"
    output: true

  tutores:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    tutores:
      name: Tutores
    alunos:
      # Give the collection a name
      name: Alunos
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
